

Norwegian = [
    "Sykkel", "Telefon", "England", "Spise", "Diamant", "Nintendo", "Mappe",
    "Munnbind", "Glass", "Rakett", "Guitar", "Pistol", "Hund", "Melk", "Saks",
    "Kniv", "Banan", "Jungel", "Dekk", "Pyramide", "Afrika", "Asia",
    "Maling", "Nisse", "Karbon", "Discman", "Bikini", "Mynt", "Konge", "Sverd",
    "Amøbe", "USB", "Mikrofon", "Kirke", "Drill", "Pakke", "Sjofør",
    "Melding", "Kaste", "Søppel", "Bombe", "Volum", "Ledning", "Zebra", "Bokstav",
    "Stige", "Panel", "Spiker", "Montasje", "Terminal", "Runde", "Admin",
    "Komedie", "Pappa", "Historie", "Spill", "Skjerm", "Poeng", "Seng", "Djevel",
    "Fotball", "Vaske", "Sopp", "Kontakt", "Person", "Nese", "Krise", "Flaske",
    "Kjøp", "Butikk", "Vaksine", "Sprøyte", "Kanon", "Krig", "Finger", "Knapp",
    "Brett", "Ungdom", "Nyse", "Avis", "Nummer", "Insekt", "Elefant", "Sofa",
    "Bart", "Enter", "Frosk", "Plate", "Sol", "Basseng", "Kino", "Madam",
    "Gardin", "Tråd", "Karakter", "Flyge", "Flamme", "Lagring", "Sjef", "Skrue",
    "Dele", "Register", "Kvinne", "Kanal", "Cider", "Tale", "Mus", "Sleike",
    "Smurf", "Pastill", "Dykker", "Platform", "Fryse", "Kald", "Varm", "Olje",
    "Album", "Musikk", "Retro", "Japan", "Korea", "Kina", "Russland", "Bue",
    "Hammer", "Kanel", "Salt", "Salat", "Barn", "Notis", "Blokk", "Fløyte",
    "Ramme", "Tarantella", "Vekt", "Svimmel", "Tall", "Engel", "Rival",
    "Spion", "Sykehus", "Frisør", "Middag", "Kanel", "Krangle", "Donald Trump",
    "Stoff", "Gud", "Farge", "Tog", "Rytter", "Magi", "Stokk", "Minus",
    "Papir", "Cowboy", "Bibel", "Konsoll", "Oppgave", "Forbryter",
    "Fengsel", "Nyhet", "Mamma", "Bestemor", "Angre", "Støvel", "Fantasi",
    "Hoppe", "Spyd", "Spy", "Fylla", "Aggresjon", "Matte", "Maleri",
    "Trang", "Aske", "Vulkan", "Spania", "Styrte", "Pilot", "Mobil",
    "Tastatur", "Kontor", "Vaskemaskin", "Kjøleskap", "Girspake", "Støv",
    "Fange", "Støy", "Serienummer", "Photoshop", "President", "Diktator",
    "Atom", "Sport", "Kidnappe", "Kaffekopp", "Båt", "Katt", "Hemmelighet",
    "Fiende", "Bryllup", "Katastrofe", "Innsjø", "Bølge", "Taper", "Knappenål",
    "Kylling", "Lunsj", "Gjerrig", "Erna Solberg", "Restaurant",
    "Oppslagstavle", "Corona", "Karantene", "Globetrotter", "Konflikt",
    "Snylter", "Nokas", "Svane", "Bergen", "Hamburger", "The Simpsons",
    "Spæll", "Podcast", "Isberg", "Titanic", "Ninja", "Protein", "Analog",
    "Pyton", "Pondus", "New York", "Oslo", "Trondheim", "Moskva", "Italia",
    "Danmark", "Sverige", "Hest", "Okse", "Traktor", "Korn", "Sjiraff",
    "Safari", "Tiger", "Skyskraper", "Hytte", "Ost", "Murer", "Sekretær",
    "Kart", "Bussrute", "Damp", "Stikke", "Bonde", "James Bond",
    "Donald Duck", "Parykk", "Disney", "Paris", "Florida", "Las Vegas",
    "Bøtte", "Marijuana", "Mexico", "Australia", "e-post", "Lærer",
    "Gaffel", "Sjøstjerne", "Maskin", "Bokser", "Programmere", "Steroider",
    "Kalkulator", "NRK", "Radio", "Diskotek", "Dverg", "Tilbakestående",
    "Apostrof", "Øl", "Datter", "Utslette", "Taco", "Ben", "Arm", "Hode",
    "Granat", "DVD", "Tøys", "Joker", "Slott", "Arbeidsplass", "Parkett",
    "Google", "Trener", "Pulp Fiction", "Quiz", "Narkoman", "Hai", "Eide",
    "Fisto", "Fotpromp", "Tisselur", "Jentesur", "Dialekt", "Tenner",
    "HTML", "Smitte", "Plagiat", "Fedex", "FRP", "Plask", "Sjakk", "Karsk",
    "Jockey", "Docking", "Speedrun", "Sjokolade", "Fritzl", "Agurk", "Snus",
    "Famicom", "Skam", "Alkoholiker"
]

Gaming = [
    "Mario", "Zelda", "Samus", "Metroid", "Hookshot", "Boss", "Level", "Glitch",
    "Game over", "Extra life", "Console", "Controller", "Bonus", "Coin", "Princess",
    "Power-up", "Nintendo", "Playstation", "RTS", "Speedrun", "Arcade", "GPU",
    "Gameboy", "Pong", "Sega", "Sonic", "Dreamcast", "SNES", "Button", "Turbo",
    "Shoot-em up", "Tetris", "Pac-man", "Donkey Kong", "Fortnite", "Multi player",
    "Story mode", "Headset", "Discord", "DLC", "Megaman", "Twitch", "Amiga", "Atari",
    "Minecraft", "Among-us", "Palette", "RGB", "SCART", "Online", "Switch", "eSport",
    "Keyboard", "Cartridge", "Expansion", "RAM", "Quake", "Call of duty", "Fifa",
    "Loading", "Mini-game", "Party game", "Grinding", "RPG", "XP", "Upgrade",
    "Framerate", "Voice chat", "Rage quit", "MOBA", "Joystick", "HOTAS", "Simulator",
    "Emulator", "Polygon", "Sound effect", "Solid Snake", "Fireball", "Pikachu",
    "Doom", "Warcraft", "Warrior", "Heal", "Hit point", "Character", "Sidekick",
    "Gear", "Armor", "Render", "Leaderboard", "Virtual Reality", "Block",
    "Weapon", "Magic", "Fanboy", "Cards", "RNG", "XBox", "Microsoft", "Unlock",
    "Secret", "Space invaders", "Enemy", "iPad", "GTA", "Wii", "Motion controlls",
    "Street fighter", "Trophy", "Snake", "FPS", "Deathmatch", "Cutscene",
    "Continue", "Champion", "Memory card", "Racing game", "Damage boost",
    "AI", "Dice", "Platform", "Puzzle", "Checkpoint", "Co-op", "NPC", "Noob",
    "Turn", "Tile", "Score", "Strategy", "Yatzi", "Fog of war", "Lag spike",
    "Bunny jump", "Quest", "Timer", "Cooldown", "Spell", "Wall kick",
    "Chest", "Floppy", "Add-on", "Power glove", "Zapper", "Isometric",
    "Difficulty", "Manual", "Cheat", "Chip tune", "Pokemon", "Collectable",
    "Castle", "Knock back", "Input lag", "Animation", "Hero", "Android",
    "Pinball", "Dungeon", "Double jump", "USB", "Repro", "Download",
    "Update", "Easter egg", "Farming", "Beat-em up", "Aimbot", "Aggro",
    "AFK", "Camping", "Crit", "Combo", "Casual", "Buff", "Exploit",
    "GG", "Konami kode", "LAN", "Nerf", "Hardcore", "Respawn", "Sandbox",
    "Sidequest", "Stats", "Sprite", "Smurf", "Tank", "Steam", "Epic"
]

Dirty = [
    "Dildo", "Pegging", "Hitler", "Satan", "Anal", "Slave", "Doggy", "Sleike",
    "Fisting", "Hemoroide", "Dirty "
]

